const wisdomQuotes = [
  'The axe that is sharpened twice cuts down the argument twice as fast.',
  'A man who owns one camel is a man. A man who owns two camels is a busy man.',
  'Do not trade your finest sheep for a mystery box. The scrolls were right again.',
  'The pyramid took a century to build. Your joke took one second. We do not accept it.',
  'Running water is not late. It merely arrives when the mountain allows.',
  'Beware the innkeeper who asks how much coin you carry before asking how you sleep.',
  'A spear thrown in anger misses twice: once the target, once your pride.',
  'The sun has set on many empires. It will also set on your streak.',
  'My neighbor planted wheat in the desert. He now owns a very expensive shovel.',
  'Trust the turtle\'s pace. He has never needed a chariot of shame.',
  'If the oracle says rain and the sky stays clear, check who fed the oracle.',
  'The young scribe wrote his name in the sand. The tide did not care.',
  'A wise man argues with a mountain once. A fool argues with it daily.',
  'The goat ate your harvest. Do not yell at the goat. The goat has no ears for your lectures.',
  'Procrastination is a fine chariot. It arrives nowhere, but it arrives comfortably.',
  'Do not poke the sleeping bear to test if it sleeps. The bear confirms faster than you hope.',
  'The shortest path between two points is often guarded by three wolves.',
  'Your pottery is lopsided. But so is the moon, and we worship it anyway.',
  'He who sells sand in the desert is either clever or has a very persuasive mother.',
  'The fish that jumps into the boat is not a blessing. It is a fish with poor judgement.',
  'A sword in the wall is a lesson. A sword in your foot is a reminder.',
  'The merchants say "limited time offer". The stars have been on sale since before you were born.',
  'Carry water before the drought, not during. The camel teaches this at dawn.',
  'Your shield is for blocking arrows, not for hiding behind your opinions.',
  'The farmer who laughs at the rain today will weep at the river tomorrow.',
  'The farmers predict weather. Trust the farmers over any oracle with a smile.',
  'A map drawn by a drunk sailor is still more reliable than your sense of direction.',
  'Do not argue with the baker about bread. He is the one with the ovens.',
  'The village idiot shouted at the eclipse. The eclipse did not apologize.',
  'Selling honey to a bear is bold. Collecting payment is mythology.',
  'Your ancestors built temples. You built a shelf. We are watching the shelf.',
  'The eagle flies alone. The vulture flies in a group. Consider this before your next feast.',
  'He who guards a gold mine guards only his own imagination.',
  'The river does not care how many times you crossed it. It only knows it is still the river.',
  'A whispered rumor travels faster than a galloping horse. Especially through walls.',
  'The scrolls say the tower of Babel fell because of poor review scores.',
  'Do not name your sword. It is a tool. Your mother named you, and look at the pressure.',
  'The man who argues with a wall wins only against the wall\'s sense of hearing.',
  'An ox that works slowly is still an ox. A man who talks slowly is a philosopher until dinner.',
  'Bury your treasure where you can remember. The dead pirates remembered nothing.',
  'The sun rises without your permission every single morning. Get used to it.',
  'If the stars could be bought, the rich would have darker nights.',
  'The baker\'s bread is round like the sun. He has not been taxed for either.',
  'Chase two rabbits and they both get away. Chase one and you are still covered in mud.',
  'The spy in your village said your secrets were safe. He was very honest. We paid him.',
  'A wheel invented in the west is still a wheel in the east. Stop arguing.',
  'Your arrow missed. The tree remembers.',
  'He who counts his coins in public is counting for the village.',
  'The fortress has strong walls. Your password is a great name for a dog.',
  'When the drum plays, dance. When it stops, your dancing is a crime.',
  'The mirror does not lie. It simply has no opinion, which is worse.',
  'Do not trade your donkey for a prophecy. The prophecy may be about donkeys.',
];

module.exports = wisdomQuotes;
